dist: trusty
sudo: required

language: node_js

node_js:
  - "8"
  - "6"

env:
  - NODE_ENV=test

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get update
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb

script:
  - jdk_switcher use oraclejdk8
  - if [ "$TRAVIS_NODE_VERSION" ~= "8" ]; then
      npm run lint;
    fi
  - npm run test:coverage
  - npm run test:e2e:test-page

after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"

notifications:
  email: false
