dist: trusty
sudo: false

language: node_js

node_js:
  - "8"
  - "6"

script:
  - if [ "$TRAVIS_NODE_VERSION" ~= "8" ]; then
      npm run lint;
    fi
  - npm run test:coverage
  - npm run test:e2e:test-page

after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"

notifications:
  email: false
